# Generated by Django 5.2 on 2025-05-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_core', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplines', models.ManyToManyField(related_name='subjects', to='disciplines.discipline')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('chapter_number', models.PositiveIntegerField(unique=True)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('estimated_duration_hours', models.PositiveIntegerField(help_text='Estimated time to complete in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ['subject', 'chapter_number'],
                'unique_together': {('subject', 'chapter_number')},
            },
        ),
    ]
